# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(612, 278)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.service_lineEdit = QtWidgets.QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.service_lineEdit.sizePolicy().hasHeightForWidth())
        self.service_lineEdit.setSizePolicy(sizePolicy)
        self.service_lineEdit.setObjectName("service_lineEdit")
        self.gridLayout.addWidget(self.service_lineEdit, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.url_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.url_lineEdit.setObjectName("url_lineEdit")
        self.gridLayout.addWidget(self.url_lineEdit, 0, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 4, 1, 1, 1)
        self.studentlist_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.studentlist_lineEdit.setEnabled(False)
        self.studentlist_lineEdit.setObjectName("studentlist_lineEdit")
        self.gridLayout.addWidget(self.studentlist_lineEdit, 5, 1, 1, 1)
        self.marksuggestion_checkBox = QtWidgets.QCheckBox(Dialog)
        self.marksuggestion_checkBox.setObjectName("marksuggestion_checkBox")
        self.gridLayout.addWidget(self.marksuggestion_checkBox, 6, 1, 1, 1)
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 3, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.username_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.gridLayout.addWidget(self.username_lineEdit, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label.setBuddy(self.studentlist_lineEdit)
        self.label_2.setBuddy(self.url_lineEdit)
        self.label_3.setBuddy(self.service_lineEdit)
        self.label_4.setBuddy(self.username_lineEdit)
        self.label_5.setBuddy(self.password_lineEdit)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.url_lineEdit, self.service_lineEdit)
        Dialog.setTabOrder(self.service_lineEdit, self.username_lineEdit)
        Dialog.setTabOrder(self.username_lineEdit, self.password_lineEdit)
        Dialog.setTabOrder(self.password_lineEdit, self.checkBox)
        Dialog.setTabOrder(self.checkBox, self.studentlist_lineEdit)
        Dialog.setTabOrder(self.studentlist_lineEdit, self.marksuggestion_checkBox)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.label.setText(_translate("Dialog", "Student List Path"))
        self.label_2.setText(_translate("Dialog", "Moodle URL"))
        self.checkBox.setText(_translate("Dialog", "Use Student List"))
        self.marksuggestion_checkBox.setText(_translate("Dialog", "Create Marksuggestions"))
        self.label_3.setText(_translate("Dialog", "Service Name"))
        self.label_4.setText(_translate("Dialog", "Moodle Username"))
        self.label_5.setText(_translate("Dialog", "Password"))
