# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(647, 219)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 3, 1, 1, 1)
        self.cancle_number_spinBox = QtWidgets.QSpinBox(Dialog)
        self.cancle_number_spinBox.setObjectName("cancle_number_spinBox")
        self.gridLayout.addWidget(self.cancle_number_spinBox, 5, 1, 1, 1)
        self.studentlist_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.studentlist_lineEdit.setEnabled(False)
        self.studentlist_lineEdit.setObjectName("studentlist_lineEdit")
        self.gridLayout.addWidget(self.studentlist_lineEdit, 4, 1, 1, 1)
        self.username_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.username_lineEdit.setObjectName("username_lineEdit")
        self.gridLayout.addWidget(self.username_lineEdit, 0, 1, 1, 2)
        self.download_pushButton = QtWidgets.QPushButton(Dialog)
        self.download_pushButton.setObjectName("download_pushButton")
        self.gridLayout.addWidget(self.download_pushButton, 2, 2, 1, 1)
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.gridLayout.addWidget(self.password_lineEdit, 1, 1, 1, 2)
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.last_download_label = QtWidgets.QLabel(Dialog)
        self.last_download_label.setObjectName("last_download_label")
        self.gridLayout.addWidget(self.last_download_label, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 7, 1, 1, 2)
        self.open_pushButton = QtWidgets.QPushButton(Dialog)
        self.open_pushButton.setObjectName("open_pushButton")
        self.gridLayout.addWidget(self.open_pushButton, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.config_label = QtWidgets.QLabel(Dialog)
        self.config_label.setObjectName("config_label")
        self.gridLayout.addWidget(self.config_label, 6, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 6, 0, 1, 1)
        self.label_5.setBuddy(self.password_lineEdit)
        self.label_4.setBuddy(self.username_lineEdit)
        self.label_6.setBuddy(self.download_pushButton)
        self.label.setBuddy(self.studentlist_lineEdit)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.username_lineEdit, self.password_lineEdit)
        Dialog.setTabOrder(self.password_lineEdit, self.download_pushButton)
        Dialog.setTabOrder(self.download_pushButton, self.checkBox)
        Dialog.setTabOrder(self.checkBox, self.studentlist_lineEdit)
        Dialog.setTabOrder(self.studentlist_lineEdit, self.open_pushButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Settings"))
        self.checkBox.setText(_translate("Dialog", "Use Student List"))
        self.download_pushButton.setText(_translate("Dialog", "Download Studentlist"))
        self.label_8.setText(_translate("Dialog", "Cancel Number"))
        self.label_5.setText(_translate("Dialog", "Password"))
        self.last_download_label.setText(_translate("Dialog", "last download: "))
        self.label_4.setText(_translate("Dialog", "Moodle Username"))
        self.open_pushButton.setText(_translate("Dialog", "Open..."))
        self.label_6.setText(_translate("Dialog", "LDAP"))
        self.label.setText(_translate("Dialog", "Student List Path"))
        self.config_label.setText(_translate("Dialog", "Config file at config.ini"))
        self.label_2.setText(_translate("Dialog", "Config"))
